"""Add swift_table

Revision ID: a449550f4562
Revises: 
Create Date: 2025-05-03 18:24:30.858940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a449550f4562'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swift_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('country_iso2', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(length=200), nullable=False),
    sa.Column('swift_code', sa.String(length=11), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('is_headquarter', sa.Boolean(), nullable=False),
    sa.Column('headquarter_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['headquarter_id'], ['swift_data.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('swift_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swift_data')
    # ### end Alembic commands ###
